### PR TITLE
Rename website in browser tab and change icon 

### PR DESCRIPTION
**Pull request by jennetturkkan**
Screen Shot 2020-11-23 at 16 09 12

### CODE REVIEW

**Review by hiba-machfej — APPROVED** [review]

**Review by louisrli — APPROVED** [review]

**Comment by louisrli** [comment]
generally you want to use a smaller logo. notice how its 56kb. thats too big for just the favicon

**Comment by louisrli** [comment]
but the one you deleted is 5kb

**Comment by jennetturkkan** [comment]
okay, i will reduce it

**Comment by jennetturkkan** [comment]
couldn't reduce to the less than 15kb :/

**Comment by jennetturkkan** [comment]
@Ammar-64

**Comment by Jamil-Bailony** [comment]
@Ammar-64 155 minutes left :))

**Pull request merged**
