### PR TITLE
Fix help button responsiveness in main banner 

### LINKED ISSUE #180: find help button on home page responsiveness
Screen Shot 2020-11-22 at 9 45 53 PM

### PR DESCRIPTION
**Pull request by jennetturkkan**
it was:
Screen Shot 2020-11-23 at 00 41 48
it became:
Screen Shot 2020-11-23 at 00 42 10

### CODE REVIEW

**Review by Jamil-Bailony — APPROVED** [review]

**Comment by Jamil-Bailony** [comment]
wait, I think this one should take all width on small screen according to the design, I did that with all sign in/up, profile buttons

image

**Review by Jamil-Bailony — COMMENTED** [review]
I think that should take 100% of width, what is the issue?

**Comment by Jamil-Bailony** [comment]
In this case, that button will be too small on mobile and hard to click (25% of the mobile screen width)

**Comment by jennetturkkan** [comment]
@Jamil-Bailony it doesn't look good. you don't see this kind of long buttons in mobile versions

**Comment by jennetturkkan** [comment]
you may want to change in profile too

**Comment by jennetturkkan** [comment]
our design for mobile version was this
Screen Shot 2020-11-23 at 01 26 58

**Review by louisrli — APPROVED** [review]

**Review by Jamil-Bailony — APPROVED** [review]

**Comment by jennetturkkan** [comment]
@Ammar-64

**Pull request merged**
