### PR TITLE
Adding link to jobs and training from home page

### PR DESCRIPTION
**Pull request by hiba-machfej**

### CODE REVIEW

**Review by jennetturkkan — APPROVED** [review]
Looks good. good work @hiba-machfej

**Review by louisrli — APPROVED** [review]
same its fine but nothing seems to be translated on jobstraininghome

**Comment by hiba-machfej** [comment]
@Ammar-64

**Comment by Ammar-64** [comment]
> @Ammar-64 
@hiba-machfej can you update the branch please

**Comment by hiba-machfej** [comment]
@Ammar-64 done

**Pull request merged**
