### PR TITLE
Carousel responsiveness fix

### LINKED ISSUE #144: Fix carousels responsiveness
fix blogs and find help responsiveness

### PR DESCRIPTION
**Pull request by jennetturkkan**
* Fixed issues with responsiveness in search help section of homepage
* Me and @hiba-machfej fixed blogs carousel responsiveness and style-related issues it had.

Screen Shot 2020-11-21 at 17 55 39
Screen Shot 2020-11-21 at 17 56 07
Screen Shot 2020-11-21 at 17 56 33

### CODE REVIEW

**Review by louisrli — APPROVED** [review]

**Comment by louisrli** [comment]
can you remove the periods on all the blog titles

**Review by hiba-machfej — CHANGES_REQUESTED** [review]
we need to match the blogs style

**Comment by louisrli** [comment]
oh if you are using cards here too, then yes, you should move it into
another component

**Comment by louisrli** [comment]
but i'd say you have to pass on that one, already the cards is a bit dicy but its technically part of a PR that existed before the freeze. i'd just merge this for now

**Review by hiba-machfej — APPROVED** [review]

**Comment by jennetturkkan** [comment]
@Ammar-64 ready to merge :)

**Pull request merged**
