### PR TITLE
add Arabic translation

### PR DESCRIPTION
**Pull request by Jamil-Bailony**
- [x] Add Arabic translation for sign in page

### CODE REVIEW

**Review by louisrli — APPROVED** [review]

**Comment by hiba-machfej** [comment]
@Ammar-64

**Review by louisrli — APPROVED** [review]

**Comment by Ammar-64** [comment]
There’s a conflict here

**Comment by Jamil-Bailony** [comment]
solved @Ammar-64

**Review by mohammad-jundi — APPROVED** [review]

**Comment by Jamil-Bailony** [comment]
@Ammar-64

**Pull request merged**
