### PR TITLE
Fix user image

### LINKED ISSUE #154: User image url and border
- [x] add border around user image

- [x] fix user url image

### PR DESCRIPTION
**Pull request by Jamil-Bailony**
- [x] add user url image

Closes #154

### CODE REVIEW

**Comment by jennetturkkan** [comment]
I already added border and fixed margins. probably you should close this PR, pull changes and add code is missing in your opinion.

**Comment by jennetturkkan** [comment]
https://github.com/ReCoded-Org/capstone-istanbul-safe_place/pull/151

**Comment by jennetturkkan** [comment]
you would want to add this only
```  
src={currentUser?.photoURL || defaultProfileImage}
```

**Review by jennetturkkan — APPROVED** [review]

**Review by louisrli — APPROVED** [review]

**Comment by jennetturkkan** [comment]
@Ammar-64

**Pull request merged**
