### PR TITLE
Homepage anchor styling

### PR DESCRIPTION
**Pull request by jennetturkkan**
* Change anchor style in opportunities and blog button in homepage. They had blue underline before

### CODE REVIEW

**Review by louisrli — APPROVED** [review]

**Review by louisrli — COMMENTED** [review]
actually this seems like it should be a mixin, called NormalLink or something.

**Review by louisrli — CHANGES_REQUESTED** [review]
refactor to common code

**Comment by jennetturkkan** [comment]
@louisrli done :)

**Review by louisrli — APPROVED** [review]

**Review by hiba-machfej — APPROVED** [review]

**Comment by hiba-machfej** [comment]
@Ammar-64

**Pull request merged**
