### PR TITLE
Blog style fix

### LINKED ISSUE #130: Our blog page: margin and check text readability
- [ ] make the margin equal

- [ ] make the shadow more white

- [ ] fix the margin on small screens

image
image

### PR DESCRIPTION
**Pull request by jennetturkkan**
* Added margin between search bar and blogs
* Fix blogs responsiveness 
Screen Shot 2020-11-21 at 16 39 13
Screen Shot 2020-11-21 at 16 39 49

### CODE REVIEW

**Comment by louisrli** [comment]
not sure im a fan of the black text on the blog images. feels like it can be made better. as they are titles, they should probably be bigger in text 

i'd also consider adding shadows or a border to the rounded images to give them texture somehow. 

or another option is to add a background to the container of the four images (a really light, rounded one)

the four images with the black text just seems a bit jarring on the white background right now

**Comment by louisrli** [comment]
play around with the opacity of the background images

https://www.nngroup.com/articles/text-over-images/

**Comment by jennetturkkan** [comment]
what do you think about title under image? @louisrli 

Screen Shot 2020-11-21 at 17 03 29

**Comment by jennetturkkan** [comment]
with shadow
Screen Shot 2020-11-21 at 17 31 50

**Comment by louisrli** [comment]
title under image is much better although still i'd add a background or
something to the title. i'd consider making it card-like (see some other
examples of blogs maybe)

generally we actually dont put text over arbitrarily-controlled images (in
this case we dont "control" the blog images so to speak, if they come from
an extra source) because of the troubles outlined in that article i sent,
so text below is much better. when we put text over images we usually do it
carefully w/ intention (as part of a design)

also remove the period in "Prevent Dating Violence." if possible

**Comment by louisrli** [comment]
is the hsadow on the text or the image?

**Comment by jennetturkkan** [comment]
> is the hsadow on the text or the image?


image

**Comment by louisrli** [comment]
looks passable i suppose, could be improved but that's up to you guys

**Comment by louisrli** [comment]
update the code and it should be fine

**Comment by jennetturkkan** [comment]
@louisrli we will try to make cards

**Comment by hiba-machfej** [comment]
Screen Shot 2020-11-21 at 7 18 13 PM
Screen Shot 2020-11-21 at 7 18 23 PM
Screen Shot 2020-11-21 at 7 18 29 PM

**Comment by hiba-machfej** [comment]
@louisrli  can I move the cards into a different component? so I can reuse the same cards in the blogs carousel in home page?

**Comment by hiba-machfej** [comment]
can you check the style too ?

**Comment by hiba-machfej** [comment]
adding cards into a single component will clean the code.

**Review by louisrli — APPROVED** [review]
it looks a lot better, actually i think the code is pretty good as it is now

**Comment by louisrli** [comment]
moving it into a new component is optional, but i'd say that because the code for the card is quite small it's not at the "necessary" part yet

**Comment by louisrli** [comment]
i would make the gap above/below the titles more symmetric. notice how theres a much larger gap below the title than above it. probably the fix is just to add more margin above the title, as more space almost never hurts

**Comment by jennetturkkan** [comment]
we thought of moving card to a different component, so we can reuse it in carousel @louisrli

**Comment by louisrli** [comment]
can you submit this PR first. and submit the other PR. make the component
common code bug fix in its own PR.

**Comment by jennetturkkan** [comment]
@Ammar-64 ready to merge

**Review by hiba-machfej — APPROVED** [review]

**Pull request merged**
