### PR TITLE
Used jobsTraining button in the home page. 

### PR DESCRIPTION
**Pull request by hiba-machfej**
Used jobsTraining buttons and header component from OpportunitiesPage to the section on the home page. 

Screen Shot 2020-11-18 at 5 05 30 PM

### CODE REVIEW

**Comment by hiba-machfej** [comment]
I had to pass the same variables 
``` 
<JobsTrainingButtons  setCardsList={setCardsList}  setFilteredCards={setCardsList}  />
```
otherwise, it was giving an error :/

**Comment by louisrli** [comment]
doesnt seem right. what error?

you're passing the same variable in twice; in that case, there's no need to have two parameters that are exactly the same thing ;)

**Comment by louisrli** [comment]
i'd check that search twice works again...and look at how you used it in the other place for comparison

**Comment by louisrli** [comment]
i'm confused why theres a param called setFilteredCards here but theres no search?

**Comment by hiba-machfej** [comment]
In the home page, we are displaying two cards without search:
but in the opportunity page, we have the search functionality.
However, both are using the same buttons and same header so I re-used them in here but if it will create a problem no need.

the homePage doesn't need filteredCardS because it doesn't have a search. but since from the opportunity page have two variables coming and only one VARIABLE from homepage.
if I pass only one variable from home page like this 
``` <JobsTrainingButtons  setCardsList={setCardsList}   /> ```

 It's giving error setFilteredCards is not function in the training buttons.




Screen Shot 2020-11-18 at 6 34 02 PM

Screen Shot 2020-11-18 at 6 34 12 PM

**Comment by louisrli** [comment]
you need to add a comment explain why it's OK to pass the same thing twice
in the line you changed. imagine you are me or your teammate or yourself 2
months from now. the code should explain it

18 Kas 2020 Çar, saat 18:37 tarihinde hiba-machfej <notifications@github.com>
şunu yazdı:

**Comment by hiba-machfej** [comment]
@louisrli ok added comment

**Review by jennetturkkan — APPROVED** [review]

**Review by louisrli — APPROVED** [review]

**Comment by hiba-machfej** [comment]
@Ammar-64

**Pull request merged**
